### ISSUE TITLE
crash and display bugs

### ISSUE THREAD

**Issue by buildaworld** [dive2Pro/roam-reference-expand#1] opened 2022-12-07 05:36 UTC
1. after check a todo list or use `/today`  it will crash the roam 

```
Roam wasn't built in a day, and we've got an error
Try closing all Roam tabs and reopen Roam.
```
2. display bug 
![image](https://user-images.githubusercontent.com/5486868/206095675-c31d2d3b-f0d9-4f3c-903b-bfb0df03e718.png)

**Comment by dive2Pro** [comment] 2022-12-07 05:58
> 1. after check a todo list or use `/today`  it will crash the roam
> 
> ```
> Roam wasn't built in a day, and we've got an error
> Try closing all Roam tabs and reopen Roam.
> ```
> 
> 2. display bug
>    ![image](https://user-images.githubusercontent.com/5486868/206095675-c31d2d3b-f0d9-4f3c-903b-bfb0df03e718.png)

hey, i don't see any infomation with this plugin, and i can't reproduce this bug myself by following your steps also.  Maybe it's caused by other plugins?

**Comment by buildaworld** [comment] 2022-12-07 07:46
> 

created a new graph and installed only 1 plugin,reproduced the bugs


Tested on 
windows app
windows chrome  108.0.5359.73 
mac app

**Comment by dive2Pro** [comment] 2022-12-07 09:36
yeah, i can reproduced the bug.  thx  for reporting it!

will fix it  asap

buildaworld ***@***.***> 于2022年12月7日周三 15:46写道：

**Comment by dive2Pro** [comment] 2022-12-21 00:46
should be fixed now, please update it in the roam depot

**Closed as completed by dive2Pro** 2022-12-21 00:46 UTC
